In [9]:
import pandas as pd
mm = pd.read_csv("megamillions.csv", header=None)
mm

                 0   1   2     3   4   5   6   7   8   9   10
0     Mega Millions  12   5  2003  12  44  15  18   1  42   4
1     Mega Millions  12   9  2003  14  15  48   4  24  41   4
2     Mega Millions  12  12  2003  16  32  46   9  45  26   4
3     Mega Millions  12  16  2003  47  16  31  24  46  47   3
4     Mega Millions  12  19  2003   5  10  39  17  35  38   3
...             ...  ..  ..   ...  ..  ..  ..  ..  ..  ..  ..
1894  Mega Millions   1  28  2022  25  44  55  16   3  13   3
1895  Mega Millions   2   1  2022  62  24  66  11  38   1   4
1896  Mega Millions   2   4  2022  61   7  34  16  44  24   4
1897  Mega Millions   2   8  2022  17  52  20  54   1   2   3
1898  Mega Millions   2  11  2022  30  24  11  23  16  24   3

[1899 rows x 11 columns]

In [10]:
for i in range(len(mm)):
    mm.iloc[i,9]

In [14]:
from datetime import datetime

def lot_num_match(input_combo, mth, dy, yr):
    
    winning_num = []
    match = 0
    for i in range(5):
        
        if mm.iloc[i,1] == mth and mm.iloc[i,2] == dy and mm.iloc[i,3]==yr:
            
            for j in range(5):
          
                for lot_num in range(len(input_combo)):
                    if mm.iloc[i,lot_num+4] == input_combo[j]:
                        match = match + 1
                        winning_num.append(mm.iloc[i,lot_num+4])
                    else:
                        pass
    
        else:
            pass
    
    print('Winning Number(s): ', winning_num)
    return match
                

    
def lot_megaball_match(input_combo, mth, dy, yr):
    
    winning_num = []
    match = 0
    for i in range(5):
        
        if mm.iloc[i,1] == mth and mm.iloc[i,2] == dy and mm.iloc[i,3]==yr:
            
            if mm.iloc[i,9] == megaball_input:
                winning_num = megaball_input
                match += 1
            else:
                pass
        else:
            pass
    
    print('Megaball: ', winning_num)
    return match
                


    
    
    
date_entry = input('Enter a date (e.g. 12/26/2021): ')
month, day, year = map(int, date_entry.split('/'))
array_input = input('Enter a list of numbers please: ').split()
array_input = [int(x) for x in array_input]
print(lot_num_match(array_input, month, day, year), 'numbers matched')

megaball_input = input('Enter Megaball number please: ')
megaball_input = int(megaball_input)
print(lot_megaball_match(megaball_input, month, day, year), "megaball number matched")

Enter a date (e.g. 12/26/2021): 12/09/2003
Enter a list of numbers please: 4 48 15 99 68
Winning Number(s):  [4, 48, 15]
3 numbers matched
Enter Megaball number please: 41
Megaball:  41
1 megaball number matched